name: My NPM package workflow
on: push
jobs:
  node-20-release:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-node@v4
          with:
            node-version: '20'
        - name: files and folders
          run: |
            pwd
            ls     


          
