name: My NPM package workflow
on: push
jobs:
  node-20-release:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/setup-node@v4
          with:
            node-version: 20
        - run: npm ci
        - run: npm test
      
