name: concurrency-1
on:
    workflow_dispatch: 
        inputs:
            environment:
                type: environment
                required: true
concurrency: concurrency-1                
jobs:
    sleep-job:
        runs-on: ubuntu-latest
        steps:
            - run: sleep 30               