name: concurrency-1
run-name: concurrency-1-${{inputs.environment}}
on:
    workflow_dispatch: 
        inputs:
            environment:
                type: environment
                required: true
concurrency: 
    group: ${{github.workflow}}-${{inputs.environment}}     
    #group: ${{github.workflow}}-${{github.ref}}
    cancel-in-progress: true
jobs:
    sleep-job:
        runs-on: ubuntu-latest
        steps:
            - run: sleep 30               