name: concurrency-1
run-name: concurrency-1-${{inputs.environment}}
on:
    workflow_dispatch: 
        inputs:
            environment:
                type: environment
                required: true
concurrency: 
    group: ${{inputs.environment}}                
    cancel-in-progress: true
jobs:
    sleep-job:
        runs-on: ubuntu-latest
        steps:
            - run: sleep 30               