name: concurrency-2
run-name: concurrency-2${{inputs.environment}}
on:
    workflow_dispatch: 
        inputs:
            environment:
                type: environment
                required: true
concurrency: 
    group: ${{github.workflow}}-${{inputs.environment}}                
    cancel-in-progress: true
jobs:
    sleep-job:
        runs-on: ubuntu-latest
        steps:
            - run: sleep 30               