name: continue-on-error
on:
    workflow_dispatch: 
        inputs:
            pass-unit-test:
                type: boolean
                default: false
jobs:
    lint-build:
        runs-on: ubuntu-latest
        steps:
            - name: lint-build
              run: echo linting and build project
    unit-test:
        runs-on: ubuntu-latest
        steps:
            - name: Running unit test
              run: |
               echo "Running the test..." 
            - name: Failing tests...
              if: ${{!inputs.pass-unit-test}}
              continue-on-error: true
              run: exit 1
                                          