name: Repo-events
on: 
    push:
    pull_request:
        types: [opened, closed]
    issues:
        types: [opened, closed]

jobs:
  repo-lab-events:
    runs-on: ubuntu-latest
    steps:
      - name: checkout-code
        uses: actions/checkout@v4
      -  run: |
          echo $GITHUB_SHA
          echo $GITHUB_REF
    