name: expression on workflow
on:
    push:
    workflow_dispatch: 
        inputs:
            debug:
                type: boolean
                default: false
jobs:
    echo:
        runs-on: ubuntu-latest
        steps:
            - name: '[debug] print startup data'
              if : ${{inputs.debug==true}}
              run: |
               echo "Triggerd by: ${{github.event_name}}"
               echo "Branch: ${{github.ref}}"
               echo  "Commit: ${{github.sha}} "
               echo "Runner Os: ${{runner.os}}"
            - name: '[debug] print when triggered from main' 
              if: ${{inputs.debug == true && github.ref == 'refs/heads/main'}}
              run: echo "I was triggered from main"
            - name: Hello
              run: echo "Hello world"
