name: Firstworkflow
run-name: ${{github.actor}} is deploying
on: [push]
jobs:
  shell-commands:
    runs-on: ubuntu-latest
    steps:
      - name: Echo a String
        run: echo "Hello world"
      - name: Multiline commands
        run: |
            nod -v
            npm -v
  parallel-job-mac:
    runs-on: macos-latest
    steps:
      - name: view SW version
        run: sw_vers
  depends-job:
    runs-on: windows-latest
    needs: shell-commands
    steps:
      - name: Echo a string
        run: Write-Output "Windows String"       
