name: manual workflow
on:
    workflow_dispatch: 
        inputs:
            name:
                description: A string Input 
                type: string
                required: true
                default: "Sabareesh"
            number:
                description: Enter a number
                type: number
                default: 4
            option:
                description: Please select an option
                type: choice
                required: true
                options:
                    - AWS
                    - Linux
                    - CCNA        
                default: "AWS" 
            boolean:
                description: CCNA completed
                required: false
                type: boolean
            environmnet:
                description: "Environment"
                type: environment
    schedule:
        - cron: "0 14 * * *"                    

jobs:
    log-info:
      runs-on: ubuntu-latest
      steps:
          - run: echo $GITHUB_REF
    input-options:
        runs-on: ubuntu-latest
        steps:
            - name: input-values
              run: |
               echo "String:${{inputs.name}}" 
               echo "The option selected:${{inputs.option}} "     
          
     
