name: manual workflow
on:
    workflow_dispatch: 
        inputs:
            name:
                description: A string Input 
                type: string
                required: true
                default: "Sabareesh"

jobs:
    log-info:
      runs-on: ubuntu-latest
      steps:
          - run: echo $GITHUB_REF
          
     
