name: matrix-1-config
on: [push]
jobs:
    node-matrix:
        continue-on-error: false
        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest]
                node-version: [ 14]
                
                include:
                    - os: windows-latest
                      node-version: 16
                      custom-variable: custom-value

                     
        runs-on: ${{matrix.os}} 
        steps:
            - name: print Matrix
              run: echo '${{toJson(matrix)}}'
            - name: Setup-node
              uses: actions/setup-node@v3
              with:
                node-version: ${{matrix.node-vs}} 
            - name: verify-node-js
              run: node -v
