name: matrix-1-config
on: [push]
jobs:
    outputs-new:
        runs-on: ubuntu-latest
        outputs:
            name: ${{steps.step1.outputs.NAME}}
        steps:
            - id: step1
              run: echo "NAME=sabareesh" >> "$GITHUB_OUTPUT"
    welcome:
        runs-on: ubuntu-latest
        needs: outputs-new  
        steps:
            - run: echo "Bye, ${{needs.outputs-new.outputs.name}}"        

        