name: Reusable workflows-Reusable Def
on:
    workflow_call: 
        inputs:
            target-directory:
                type: string
                required: true
        outputs:
          build-status:
            description: THe Status of the build Process
            value: ${{jobs.deploy.outputs.build-status}}
          url:
            description: THe URL of the deployed version
            value: ${{jobs.deploy.outputs.url}}  


jobs:
    deploy:
        runs-on: ubuntu-latest
        outputs:
          build-status: ${{steps.build.outputs.build-status}}
          url: ${{steps.deploy.outputs.url}}
        steps:
            - name: Checkout-repo
              uses: actions/checkout@v4
            - name: build
              id:  build
              run: |
               echo "Building using Direc ${{inputs.target-directory}}"
               echo "build-status=sucess" >> "$GITHUB_OUTPUT"
            - name: Deploy
              id: deploy
              run: |
               echo "Deploying build artifacts"
               echo "url=https://www.google.com" >> "$GITHUB_OUTPUT"
