name: creating-reusable-wf
on:
    workflow_call: 
        inputs:
            target-directory:
                type: string
        outputs:
            build-status:
                description: The Status of the build process
                value: ${{jobs.deploy.outputs.build-status}}
            url:
                description: The URL of the deployed version
                value: ${{jobs.deploy.outputs.url}}
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: checkout repo
              uses: actions/checkout@v4
            - name: Build
              id: build
              run: |
               echo "Building using directory ${{inputs.target-directory}}"
               echo "build-status=success" >> "$GITHUB_OUTPUT"
            - name: Deploy
              id: deploy
              run: |
               echo "Deploying Build artifacts"
               echo "url=https://www.google.com" >> "$GITHUB_OUTPUT"

        
        
