name: Reuse-wf-lab
on:
    workflow_dispatch: 
jobs:
    deploy:
        uses: ./.github/workflows/reusable-lab-called-wf.yaml
        with:
            target-directory: ec2-user
    print-outputs:
        runs-on: ubuntu-latest
        needs: deploy
        steps:
            - name: print output
              run: |
               echo "build status ${{needs.deploy.outputs.build-status}}"
               echo "URL ${{needs.deploy.outputs.url}}"



