name: working direcory and shells
on: [push]
jobs:
    display-the-working-directory:
        runs-on: ubuntu-latest
        steps:
            - name: Display working direcory and List of files
              run: |
                pwd
                ls -a
                echo $GITHUB_SHA
                echo $GITHUB_REPOSITORY
                echo $GITHUB_WORKSPACE

