name: timeout-workflow
on:  [push]
jobs:
    job-1:
        runs-on: ubuntu-latest
        timeout-minutes: 1
        steps:
            - name: step-1
              run: sleep 90
            - name: step-2
              id: step-2
              continue-on-error: true
              run: exit 1
            - name: runs on step 2 failure
              if: failure() && steps.step-2.conclusion == 'failure'
              run: echo "Step2 failed"
            - name: Runs on failure
              if: failure()
              run: echo failure
